---
features:
  - |
    **[CCI]** Add new data source ``data_source/opentelekomcloud_cci_configmaps_v2`` (`#3338 <https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/pull/3338>`_).
  - |
    **[CCI]** Add new data source ``data_source/opentelekomcloud_cci_secrets_v2`` (`#3338 <https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/pull/3338>`_).
  - |
    **[CCI]** Add new data source ``data_source/opentelekomcloud_cci_pods_v2`` (`#3338 <https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/pull/3338>`_).
