dependencies:
  - changed-files:
      - any-glob-to-any-file:
        - go.mod
        - go.sum
        - vendor/**/*
documentation:
  - changed-files:
      - any-glob-to-any-file:
        - docs/**/*
        - README.md
changelog:
  - changed-files:
      - any-glob-to-any-file:
        - CHANGELOG.md
