run:
  deadline: 12m10s
  modules-download-mode: readonly

issues:
  max-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - deadcode
    - durationcheck
    - errcheck
    - gofmt
    - gosimple
    - ineffassign
    - staticcheck
    - unconvert
    - varcheck
    - vet

linters-settings:
  misspell:
    ignore-words:
      - unknwon
  staticcheck:
    checks:
      - all
      - '-SA1019' # disable the rule SA1019
