version: "2"
run:
  timeout: 12m10s
  modules-download-mode: readonly
linters:
  default: none
  enable:
    - asciicheck
    - errcheck
    - gocritic
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused
    - whitespace
  settings:
    misspell:
      ignore-rules:
        - unknwon
    staticcheck:
      checks:
        - all
        - -SA1019
        - -ST1003
        - -QF1003
        - -S1009
        - -ST1005
        - -QF1001
        - -QF1007
        - -QF1008
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
