# Visit https://goreleaser.com for documentation on how to customize this
# behavior.
before:
  hooks:
    # this is just an example and not a requirement for provider building/publishing
    - go mod tidy
builds:
  - env:
      # goreleaser does not work with CGO, it could also complicate
      # usage by users in CI/CD systems like Terraform Cloud where
      # they are unable to install libraries.
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X=github.com/opentelekomcloud/terraform-provider-opentelekomcloud/version.ProviderVersion={{ .Version }}'
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
      # Linux only:
      # arm 8
      - goos: freebsd
        goarch: arm64
      - goos: windows
        goarch: arm64
      # arm 6
      - goos: darwin
        goarch: arm
      - goos: freebsd
        goarch: arm
      - goos: windows
        goarch: arm
    binary: '{{ .ProjectName }}_v{{ .Version }}'  # this `v` is absolutely required - in CI `v` is stripped for some reason
archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
changelog:
  use: git
  filters:
    exclude:
      - '^ci:'
      - '^reno:'
      - '^release:'
      - '^github:'
      - '^acceptance:'
release:
  # Visit your project's GitHub Releases page to publish this release.
  github:
    owner: opentelekomcloud
    name: terraform-provider-opentelekomcloud
  footer: |
    **Full Changelog**: https://docs-beta.otc.t-systems.com/releasenotes/terraform-provider-opentelekomcloud#{{ replace .Tag "." "-" }}
  prerelease: auto
