---
- project:
    merge-mode: squash-merge
    default-branch: devel
    templates:
      - release-notes-jobs
    check:
      jobs:
        - golang-make-test
        - golang-make-vet
        - goreleaser-build:
            nodeset: fedora-32-large
    gate:
      jobs:
        - golang-make-test
        - golang-make-vet
        - goreleaser-build:
            nodeset: fedora-32-large
    tag:
      jobs:
        - release-goreleaser:
            nodeset: fedora-32-large
