---
- job:
    name: terraform-functional
    description: |
      Run Terraform acceptance tests.
    parent: golang-make-functional
    pre-run: playbooks/infra-pre.yaml
    post-run: playbooks/infra-post.yaml

- job:
    name: tflint
    parent: golang-make
    vars:
      make_command: vet

- project:
    merge-mode: squash-merge
    default-branch: devel
    templates:
      - release-notes-jobs
    check:
      jobs:
        - golangci-lint:
            vars:
              golangci_lint_version: 1.41.1
        - golang-make-test
        - golang-make-vet
        - tflint
        - goreleaser-build:
            nodeset: fedora-32-large
    check-post:
      jobs:
        - terraform-functional
    gate:
      jobs:
        - golangci-lint:
            vars:
              golangci_lint_version: 1.41.1
        - golang-make-test
        - golang-make-vet
        - tflint
        - goreleaser-build:
            nodeset: fedora-32-large
    tag:
      jobs:
        - release-goreleaser:
            nodeset: fedora-32-large
