---
- job:
    name: terraform-functional
    description: |
      Run Terraform acceptance tests.
    parent: golang-make-functional
    pre-run: playbooks/infra-pre.yaml
    post-run: playbooks/infra-post.yaml

- job:
    name: tflint
    parent: golang-make
    vars:
      make_command: tflint

- project:
    merge-mode: squash-merge
    vars:
      functest_project_name: "eu-de_zuul_tf"
      go_version: "1.19.0"
    default-branch: devel
    templates:
      - release-notes-jobs
    check:
      jobs:
        - otc-golangci-lint
        - golang-make-test
        - golang-make-vet
        - tflint
        - goreleaser-build
    check-post:
      jobs:
        - terraform-functional
    gate:
      jobs:
        - otc-golangci-lint
        - golang-make-test
        - golang-make-vet
        - tflint
        - goreleaser-build
    tag:
      jobs:
        - release-goreleaser
