---
- project:
    merge-mode: squash-merge
    check:
      jobs:
        - golang-make-test
        - golang-make-vet
        - goreleaser-build:
            voting: false
    gate:
      jobs:
        - golang-make-test
        - golang-make-vet
        - goreleaser-build:
            voting: false
    tag:
      jobs:
        - release-goreleaser
