---
- job:
    name: golang-make-website-test
    parent: golang-make
    pre-run: playbooks/pre.yaml
    vars:
      make_command: website-test
      make_env:
        GOPATH: "{{ ansible_user_dir }}/go"

- project:
    merge-mode: squash-merge
    check:
      jobs:
        - golang-make-test
        - golang-make-vet
        #- golang-make-website-test
        #NEED TO BE FIXED: in #577, #588
        - goreleaser-build
    gate:
      jobs:
        - golang-make-test
        - golang-make-vet
        #- golang-make-website-test
        #NEED TO BE FIXED: in #577, #588
        - goreleaser-build
    tag:
      jobs:
        - release-goreleaser
