---
- job:
    name: tflint
    parent: golang-make
    vars:
      make_command: tflint

- project:
    merge-mode: squash-merge
    vars:
      functest_project_name: "eu-de_zuul_tf"
    default-branch: devel
    templates:
      - release-notes-jobs
    check:
      jobs:
        - otc-golangci-lint
        - golang-make-test
        - golang-make-vet
        - goreleaser-build
    check-post:
      jobs:
        - terraform-functional
    gate:
      jobs:
        - otc-golangci-lint
        - golang-make-test
        - golang-make-vet
        - goreleaser-build
    tag:
      jobs:
        - release-goreleaser
