variable project_name {}
variable project_desc {}
variable domain_id {}
variable parent_id {}
variable user_name {}
variable user_desc {}
variable user_passd {}
variable user_status {}
variable group_name {}
variable group_desc {}
variable role_name {}
variable region {}
