variable flavor_id_as {}
variable image_id_as {}
variable volume_size_as {}
variable volume_type_as {}
variable vpc_name_as {}
variable vpc_cidr_as {}
variable subnet_name1_as {}
variable subnet_cidr1_as {}
variable subnet_gateway_ip1_as {}
variable primary_dns_as {}
variable secondary_dns_as {}
variable secgroup_name_as {}
variable region_as {}
variable availability_zone_as {}
variable key_name_as {}
#variable public_key_as {}
variable alarm_id {}
variable listenerid {}
