---
- hosts: localhost
  tasks:
    - name: Set initial facts
      set_fact:
        network_name: "network_default"
        subnet_name: "subnet_default"
        router_name: "router_default"

    - name: Create network
      os_network:
        cloud: tf
        state: present
        name: "{{ network_name }}"

    - name: Create subnet
      os_subnet:
        cloud: tf
        state: present
        name: "{{ subnet_name }}"
        network_name: "{{ network_name }}"
        cidr: 192.168.0.0/24
        dns_nameservers:
          - 100.125.4.25
          - 1.1.1.1

    - name: Create router
      os_router:
        cloud: tf
        name: "{{ router_name }}"
        state: present
        network: admin_external_net
        enable_snat: true
        interfaces:
          - net: "{{ network_name }}"
            subnet: "{{ subnet_name }}"
