---
- project:
    merge-mode: squash-merge
    default-branch: devel
    templates:
      - release-notes-jobs
    check:
      jobs:
        - golangci-lint:
            vars:
              golangci_lint_version: 1.41.1
        - golang-make-test
        - golang-make-vet
        - tflint
        - goreleaser-build:
            nodeset: fedora-32-large
    gate:
      jobs:
        - golangci-lint:
            vars:
              golangci_lint_version: 1.41.1
        - golang-make-test
        - golang-make-vet
        - tflint
        - goreleaser-build:
            nodeset: fedora-32-large
    tag:
      jobs:
        - release-goreleaser:
            nodeset: fedora-32-large
